# Generated by Django 4.0.3 on 2022-03-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='catgories/images')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Комлект',
                'verbose_name_plural': 'Комплекты',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategories/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('vendor_code', models.CharField(max_length=255, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Размер Скидки')),
                ('sale', models.BooleanField(default=False, verbose_name='На Скидке')),
                ('hit', models.BooleanField(default=False, verbose_name='Хит Продаж')),
                ('image', models.ImageField(upload_to='products/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='products/images')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colors', verbose_name='Цвет')),
                ('fabric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.fabric', verbose_name='Материал')),
                ('prod_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.set', verbose_name='Комплект')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('date_added',),
            },
        ),
    ]
