# Generated by Django 3.2.7 on 2022-07-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('image', models.ImageField(upload_to='goo_on_credit/images/', verbose_name='Картинка товара')),
                ('credit_amount', models.IntegerField(default=0, verbose_name='Размер кредита')),
                ('date_end', models.DateTimeField(auto_now=True, verbose_name='Срок действия кредита')),
            ],
            options={
                'verbose_name': 'Товар в кредит',
                'verbose_name_plural': 'Товары в кредит',
                'db_table': 'goodcredit',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('image', models.ImageField(upload_to='stock/images/', verbose_name='Картинка товара')),
                ('stock_amount', models.IntegerField(default=0, verbose_name='Размер акции')),
                ('date_end', models.DateTimeField(auto_now=True, verbose_name='Срок действия акции')),
            ],
            options={
                'verbose_name': 'Товар по акции',
                'verbose_name_plural': 'Товары по акции',
                'db_table': 'stock',
            },
        ),
    ]
